# Generated by Django 5.0.1 on 2024-02-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa_app', '0002_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
