# Generated by Django 5.0.1 on 2024-03-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa_app', '0006_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
