# Generated by Django 5.0.1 on 2024-03-18 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa_app', '0008_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claass_no',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_no', models.CharField(blank=True, max_length=100, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_class', to=settings.AUTH_USER_MODEL, verbose_name='admin_class')),
            ],
        ),
    ]
