# Generated by Django 5.0.1 on 2024-03-19 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa_app', '0011_user_class_rooom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='class_room',
        ),
    ]
