# Generated by Django 5.0.1 on 2024-03-20 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa_app', '0017_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='teacher',
        ),
    ]
