# Generated by Django 5.0.1 on 2024-03-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa_app', '0018_remove_notification_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='to_see',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
