# Generated by Django 5.0.1 on 2024-03-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa_app', '0019_notification_to_see'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
