# Generated by Django 5.0.1 on 2024-03-20 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa_app', '0020_alter_notification_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
